### ISSUE TITLE
Discourse should be listed instead of Privacy Guides and Techlore forums

### ISSUE THREAD

**Issue by Mikaela** [bitwarden/passkeys-index#42]
Currently the list contains Privacy Guides Forum and Techlore Discussions, which I find weird as passkeys are a Discourse feature and nothing specific to Privacy Guides Forum or Techlore Discussions.

- https://meta.discourse.org/t/passwordless-login-using-passkeys/285589

Otherwise I wonder if every countless Discourse instance should be listed separately including [the one by Bitwarden](https://community.bitwarden.com/)?

**Comment by mark-youssef-bitwarden** [comment]
Yes that makes sense to me. I don't think we can include every single discourse site so we'll just settle with listing Discourse.
