### ISSUE TITLE
Authentik supports passkeys

### ISSUE THREAD

**Issue by Mikaela** [bitwarden/passkeys-index#43]
Authentik is an open-source identity and access management solution and it supports passkeys including for login without having to enter username or password.

- https://goauthentik.io
- https://github.com/goauthentik/authentik
- https://docs.goauthentik.io/docs/flow/stages/authenticator_validate/#passwordless-authentication

I am mostly seeing at https://login.pikaviestin.fi personally, but I understand it to be widely used.

**Comment by mark-youssef-bitwarden** [comment]
Thanks! Authentik is added to the list
