### ISSUE TITLE
Self-hostable git forges Forgejo, Gitea & GitLab all support passkeys

### ISSUE THREAD

**Issue by Mikaela** [bitwarden/passkeys-index#44]
- [ ] https://forgejo.org
- [ ] https://about.gitea.com
- [ ] https://about.gitlab.com

-----

I apologise for opening multiple issues in quick succession, I think this is all where I know of passkeys support having set it up with Bitwarden, that weren't already listed.

**Comment by mark-youssef-bitwarden** [comment]
Thanks for the contribution!
I was a bit hesitant to add forejo since I couldn't find any official documentation, but it does look they implement webauthn in their [repo](https://codeberg.org/forgejo/forgejo/src/branch/forgejo/routers/web/auth/webauthn.go) so I'll allow it 😄
