### ISSUE TITLE
[Suggestion] Merge `passkey-index.md` into README

### ISSUE THREAD

**Issue by gwoods22** [bitwarden/passkeys-index#7]
To increase the usability of this repo, especially for non-developers who may not be familiar with Github, it would be nice to have the list of supported sites in the repo README. Then if one wanted to share this list with a friend who is interested in passkey support, we could simply share the repo URL instead of the file URL. Currently the repo home page showing the README doesn't provide much useful info.

Appreciate that there may have been reasoning for separating the files but thought I'd at least propose this change, especially if there was non-developers viewing the page.

**Comment by bw-rl** [comment]
Thanks for the input. We're looking at reorganizing the passwordless repo soon and would make some structural changes then.
